# Generated by Django 2.2.10 on 2020-11-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20201117_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_by_user',
            field=models.CharField(max_length=255),
        ),
    ]
