# Generated by Django 2.2.10 on 2020-11-17 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
