# Generated by Django 2.2.10 on 2020-11-17 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='belong_to_poll',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='poll.Poll'),
        ),
    ]
